using Microsoft.EntityFrameworkCore;
using MusicStore.Data;

namespace MusicStore.Models
{
    public class SeedData_Albums
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {


            using (var context = new ApplicationDbContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<ApplicationDbContext>>()))
            {

                if (context.Albums.Any())
                {
                    return;   // DB has been seeded
                }
                context.Albums.AddRange(

                    new Album { Title = "A Copland Celebration, Vol. I", GenreId = 10, Price = 99, ArtistId = 1, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Worlds", GenreId = 2, Price = 99, ArtistId = 2, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "For Those About To Rock We Salute You", GenreId = 1, Price = 99, ArtistId = 3, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Let There Be Rock", GenreId = 1, Price = 99, ArtistId = 3, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Balls to the Wall", GenreId = 1, Price = 99, ArtistId = 4, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Restless and Wild", GenreId = 1, Price = 99, ArtistId = 4, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Górecki: Symphony No. 3", GenreId = 10, Price = 99, ArtistId = 5, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Big Ones", GenreId = 1, Price = 99, ArtistId = 6, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Quiet Songs", GenreId = 2, Price = 99, ArtistId = 7, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Jagged Little Pill", GenreId = 1, Price = 99, ArtistId = 8, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Facelift", GenreId = 1, Price = 99, ArtistId = 10, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Frank", GenreId = 9, Price = 99, ArtistId = 11, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Ring My Bell", GenreId = 5, Price = 99, ArtistId = 12, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Chill: Brazil (Disc 2)", GenreId = 7, Price = 99, ArtistId = 13, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Warner 25 Anos", GenreId = 2, Price = 99, ArtistId = 13, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Plays Metallica By Four Cellos", GenreId = 3, Price = 99, ArtistId = 14, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Revelations", GenreId = 4, Price = 99, ArtistId = 15, AlbumArtUrl = "/Content/Images/placeholder.gif" },
                    new Album { Title = "Audioslave", GenreId = 1, Price = 99, ArtistId = 15, AlbumArtUrl = "/Content/Images/placeholder.gif" }
                    
                );


                context.SaveChanges();
            }
        }
    }
}

//new Album { Title = "The Best Of Men At Work", GenreId = 1, Price = 99, ArtistId = "Men At Work", AlbumArtUrl = "/Content/Images/placeholder.gif" },
//, new Album { Title = "The Last Night of the Proms", GenreId = 10, Price = 99, ArtistId = "Barry Wordsworth & BBC Concert Orchestra", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Sibelius: Finlandia", GenreId = 10, Price = 99, ArtistId = "Berliner Philharmoniker & Hans Rosbaud", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Mozart: Symphonies Nos. 40 & 41", GenreId = 10, Price = 99, ArtistId = "Berliner Philharmoniker & Herbert Von Karajan", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Best Of Billy Cobham", GenreId = 2, Price = 99, ArtistId = "Billy Cobham", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", GenreId = 3, Price = 99, ArtistId = "Black Label Society", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", GenreId = 3, Price = 99, ArtistId = "Black Label Society", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Black Sabbath Vol. 4 (Remaster)", GenreId = 3, Price = 99, ArtistId = "Black Sabbath", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Black Sabbath", GenreId = 3, Price = 99, ArtistId = "Black Sabbath", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Carmina Burana", GenreId = 10, Price = 99, ArtistId = "Boston Symphony Orchestra & Seiji Ozawa", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "A Soprano Inspired", GenreId = 10, Price = 99, ArtistId = "Britten Sinfonia, Ivor Bolton & Lesley Garrett", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Chemical Wedding", GenreId = 3, Price = 99, ArtistId = "Bruce Dickinson", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Prenda Minha", GenreId = 7, Price = 99, ArtistId = "Caetano Veloso", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Sozinho Remix Ao Vivo", GenreId = 7, Price = 99, ArtistId = "Caetano Veloso", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Cake: B-Sides and Rarities", GenreId = 4, Price = 99, ArtistId = "Cake", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Carried to Dust (Bonus Track Version)", GenreId = 4, Price = 99, ArtistId = "Calexico", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Cássia Eller - Sem Limite [Disc 1]", GenreId = 7, Price = 99, ArtistId = "Cássia Eller", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Le Freak", GenreId = 5, Price = 99, ArtistId = "Chic", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Scheherazade", GenreId = 10, Price = 99, ArtistId = "Chicago Symphony Orchestra & Fritz Reiner", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Minha Historia", GenreId = 7, Price = 99, ArtistId = "Chico Buarque", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Afrociberdelia", GenreId = 7, Price = 99, ArtistId = "Chico Science & Nação Zumbi", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Da Lama Ao Caos", GenreId = 7, Price = 99, ArtistId = "Chico Science & Nação Zumbi", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Carry On", GenreId = 4, Price = 99, ArtistId = "Chris Cornell", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "SCRIABIN: Vers la flamme", GenreId = 10, Price = 99, ArtistId = "Christopher O'Riley", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Acústico MTV [Live]", GenreId = 8, Price = 99, ArtistId = "Cidade Negra", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Cidade Negra - Hits", GenreId = 8, Price = 99, ArtistId = "Cidade Negra", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Na Pista", GenreId = 7, Price = 99, ArtistId = "Cláudio Zoli", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Chronicle, Vol. 1", GenreId = 1, Price = 99, ArtistId = "Creedence Clearwater Revival", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Chronicle, Vol. 2", GenreId = 1, Price = 99, ArtistId = "Creedence Clearwater Revival", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Into The Light", GenreId = 1, Price = 99, ArtistId = "David Coverdale", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Come Taste The Band", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Deep Purple In Rock", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Fireball", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Machine Head", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "MK III The Final Concerts [Disc 1]", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Purpendicular", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Slaves And Masters", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Stormbringer", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Battle Rages On", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Final Concerts (Disc 2)", GenreId = 1, Price = 99, ArtistId = "Deep Purple", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Outbreak", GenreId = 2, Price = 99, ArtistId = "Dennis Chambers", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Djavan Ao Vivo - Vol. 02", GenreId = 7, Price = 99, ArtistId = "Djavan", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Djavan Ao Vivo - Vol. 1", GenreId = 7, Price = 99, ArtistId = "Djavan", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "MacArthur Park Suite", GenreId = 5, Price = 99, ArtistId = "Donna Summer", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Un-Led-Ed", GenreId = 1, Price = 99, ArtistId = "Dread Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Best of Ed Motta", GenreId = 7, Price = 99, ArtistId = "Ed Motta", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Adams, John: The Chairman Dances", GenreId = 10, Price = 99, ArtistId = "Edo de Waart & San Francisco Symphony", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Elis Regina-Minha História", GenreId = 7, Price = 99, ArtistId = "Elis Regina", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Pachelbel: Canon & Gigue", GenreId = 10, Price = 99, ArtistId = "English Concert & Trevor Pinnock", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Unplugged", GenreId = 7, Price = 99, ArtistId = "Eric Clapton", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Cream Of Clapton", GenreId = 6, Price = 99, ArtistId = "Eric Clapton", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Unplugged", GenreId = 6, Price = 99, ArtistId = "Eric Clapton", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Respighi:Pines of Rome", GenreId = 10, Price = 99, ArtistId = "Eugene Ormandy", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Strauss: Waltzes", GenreId = 10, Price = 99, ArtistId = "Eugene Ormandy", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "King For A Day Fool For A Lifetime", GenreId = 1, Price = 99, ArtistId = "Faith No More", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Deixa Entrar", GenreId = 7, Price = 99, ArtistId = "Falamansa", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "In Your Honor [Disc 1]", GenreId = 1, Price = 99, ArtistId = "Foo Fighters", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "In Your Honor [Disc 2]", GenreId = 1, Price = 99, ArtistId = "Foo Fighters", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Colour And The Shape", GenreId = 1, Price = 99, ArtistId = "Foo Fighters", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bongo Fury", GenreId = 1, Price = 99, ArtistId = "Frank Zappa & Captain Beefheart", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Roda De Funk", GenreId = 7, Price = 99, ArtistId = "Funk Como Le Gusta", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Quanta Gente Veio Ver (Live)", GenreId = 7, Price = 99, ArtistId = "Gilberto Gil", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Quanta Gente Veio ver--Bônus De Carnaval", GenreId = 2, Price = 99, ArtistId = "Gilberto Gil", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Faceless", GenreId = 3, Price = 99, ArtistId = "Godsmack", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Meus Momentos", GenreId = 7, Price = 99, ArtistId = "Gonzaguinha", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Nielsen: The Six Symphonies", GenreId = 10, Price = 99, ArtistId = "Göteborgs Symfoniker & Neeme Järvi", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Appetite for Destruction", GenreId = 1, Price = 99, ArtistId = "Guns N' Roses", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Use Your Illusion I", GenreId = 1, Price = 99, ArtistId = "Guns N' Roses", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Use Your Illusion II", GenreId = 3, Price = 99, ArtistId = "Guns N' Roses", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Blue Moods", GenreId = 2, Price = 99, ArtistId = "Incognito", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "A Matter of Life and Death", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Brave New World", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Fear Of The Dark", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live At Donington 1992 (Disc 1)", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live At Donington 1992 (Disc 2)", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Rock In Rio [CD2]", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Number of The Beast", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The X Factor", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Virtual XI", GenreId = 1, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "A Real Dead One", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "A Real Live One", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live After Death", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "No Prayer For The Dying", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Piece Of Mind", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Powerslave", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Rock In Rio [CD1]", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Rock In Rio [CD2]", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Seventh Son of a Seventh Son", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Somewhere in Time", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Number of The Beast", GenreId = 3, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Iron Maiden", GenreId = 6, Price = 99, ArtistId = "Iron Maiden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Mascagni: Cavalleria Rusticana", GenreId = 10, Price = 99, ArtistId = "James Levine", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Emergency On Planet Earth", GenreId = 1, Price = 99, ArtistId = "Jamiroquai", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Are You Experienced?", GenreId = 1, Price = 99, ArtistId = "Jimi Hendrix", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Surfing with the Alien (Remastered)", GenreId = 1, Price = 99, ArtistId = "Joe Satriani", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Jorge Ben Jor 25 Anos", GenreId = 7, Price = 99, ArtistId = "Jorge Ben", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Jota Quest-1995", GenreId = 7, Price = 99, ArtistId = "Jota Quest", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Living After Midnight", GenreId = 3, Price = 99, ArtistId = "Judas Priest", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Weill: The Seven Deadly Sins", GenreId = 10, Price = 99, ArtistId = "Kent Nagano and Orchestre de l'Opéra de Lyon", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Kiss", GenreId = 1, Price = 99, ArtistId = "Kiss", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Unplugged [Live]", GenreId = 1, Price = 99, ArtistId = "Kiss", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "BBC Sessions [Disc 1] [Live]", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "BBC Sessions [Disc 2] [Live]", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Coda", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Houses Of The Holy", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "In Through The Out Door", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "IV", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Led Zeppelin I", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Led Zeppelin II", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Led Zeppelin III", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Physical Graffiti [Disc 1]", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Physical Graffiti [Disc 2]", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Presence", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Song Remains The Same (Disc 1)", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Song Remains The Same (Disc 2)", GenreId = 1, Price = 99, ArtistId = "Led Zeppelin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Mais Do Mesmo", GenreId = 7, Price = 99, ArtistId = "Legião Urbana", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Hits", GenreId = 8, Price = 99, ArtistId = "Lenny Kravitz", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Hits", GenreId = 1, Price = 99, ArtistId = "Lenny Kravitz", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Hits", GenreId = 3, Price = 99, ArtistId = "Lenny Kravitz", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Tchaikovsky: The Nutcracker", GenreId = 10, Price = 99, ArtistId = "London Symphony Orchestra & Sir Charles Mackerras", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Duos II", GenreId = 7, Price = 99, ArtistId = "Luciana Souza/Romero Lubambo", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Chill: Brazil (Disc 1)", GenreId = 7, Price = 99, ArtistId = "Marcos Valle", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Misplaced Childhood", GenreId = 1, Price = 99, ArtistId = "Marillion", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Barulhinho Bom", GenreId = 7, Price = 99, ArtistId = "Marisa Monte", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Szymanowski: Piano Works, Vol. 1", GenreId = 10, Price = 99, ArtistId = "Martin Roscoe", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "...And Justice For All", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Black Album", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Garage Inc. (Disc 1)", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Garage Inc. (Disc 2)", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Load", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Master Of Puppets", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "ReLoad", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Ride The Lightning", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "St. Anger", GenreId = 3, Price = 99, ArtistId = "Metallica", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Berlioz: Symphonie Fantastique", GenreId = 10, Price = 99, ArtistId = "Michael Tilson Thomas & San Francisco Symphony", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Prokofiev: Romeo & Juliet", GenreId = 10, Price = 99, ArtistId = "Michael Tilson Thomas & San Francisco Symphony", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Miles Ahead", GenreId = 2, Price = 99, ArtistId = "Miles Davis", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Essential Miles Davis [Disc 1]", GenreId = 2, Price = 99, ArtistId = "Miles Davis", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Essential Miles Davis [Disc 2]", GenreId = 2, Price = 99, ArtistId = "Miles Davis", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Milton Nascimento Ao Vivo", GenreId = 7, Price = 99, ArtistId = "Milton Nascimento", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Minas", GenreId = 7, Price = 99, ArtistId = "Milton Nascimento", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Motley Crue Greatest Hits", GenreId = 3, Price = 99, ArtistId = "Mötley Crüe", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Ace Of Spades", GenreId = 3, Price = 99, ArtistId = "Motörhead", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Mozart: Chamber Music", GenreId = 10, Price = 99, ArtistId = "Nash Ensemble", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Best of Beethoven", GenreId = 10, Price = 99, ArtistId = "Nicolaus Esterhazy Sinfonia", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Nevermind", GenreId = 1, Price = 99, ArtistId = "Nirvana", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Compositores", GenreId = 1, Price = 99, ArtistId = "O Terço", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Olodum", GenreId = 7, Price = 99, ArtistId = "Olodum", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bach: The Brandenburg Concertos", GenreId = 10, Price = 99, ArtistId = "Orchestra of The Age of Enlightenment", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Acústico MTV", GenreId = 7, Price = 99, ArtistId = "Os Paralamas Do Sucesso", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Arquivo II", GenreId = 7, Price = 99, ArtistId = "Os Paralamas Do Sucesso", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Arquivo Os Paralamas Do Sucesso", GenreId = 7, Price = 99, ArtistId = "Os Paralamas Do Sucesso", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Tribute", GenreId = 3, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bark at the Moon (Remastered)", GenreId = 1, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Blizzard of Ozz", GenreId = 1, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Diary of a Madman (Remastered)", GenreId = 1, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "No More Tears (Remastered)", GenreId = 1, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Speak of the Devil", GenreId = 1, Price = 99, ArtistId = "Ozzy Osbourne", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Walking Into Clarksdale", GenreId = 1, Price = 99, ArtistId = "Page & Plant", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Beast Live", GenreId = 1, Price = 99, ArtistId = "Paul D'Ianno", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live On Two Legs [Live]", GenreId = 1, Price = 99, ArtistId = "Pearl Jam", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Riot Act", GenreId = 1, Price = 99, ArtistId = "Pearl Jam", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Ten", GenreId = 1, Price = 99, ArtistId = "Pearl Jam", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Vs.", GenreId = 1, Price = 99, ArtistId = "Pearl Jam", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Dark Side Of The Moon", GenreId = 1, Price = 99, ArtistId = "Pink Floyd", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Hits I", GenreId = 1, Price = 99, ArtistId = "Queen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Greatest Hits II", GenreId = 1, Price = 99, ArtistId = "Queen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "News Of The World", GenreId = 1, Price = 99, ArtistId = "Queen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "New Adventures In Hi-Fi", GenreId = 1, Price = 99, ArtistId = "R.E.M.", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Raul Seixas", GenreId = 1, Price = 99, ArtistId = "Raul Seixas", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "By The Way", GenreId = 1, Price = 99, ArtistId = "Red Hot Chili Peppers", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Californication", GenreId = 1, Price = 99, ArtistId = "Red Hot Chili Peppers", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Purcell: The Fairy Queen", GenreId = 10, Price = 99, ArtistId = "Roger Norrington, London Classical Players", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Haydn: Symphonies 99 - 104", GenreId = 10, Price = 99, ArtistId = "Royal Philharmonic Orchestra & Sir Thomas Beecham", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Retrospective I (1974-1980)", GenreId = 1, Price = 99, ArtistId = "Rush", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Santana - As Years Go By", GenreId = 1, Price = 99, ArtistId = "Santana", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Santana Live", GenreId = 1, Price = 99, ArtistId = "Santana", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Supernatural", GenreId = 1, Price = 99, ArtistId = "Santana", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Handel: The Messiah (Highlights)", GenreId = 10, Price = 99, ArtistId = "Scholars Baroque Ensemble", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Prokofiev: Symphony No.1", GenreId = 10, Price = 99, ArtistId = "Sergei Prokofiev & Yuri Temirkanov", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Wagner: Favourite Overtures", GenreId = 10, Price = 99, ArtistId = "Sir Georg Solti & Wiener Philharmoniker", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Maquinarama", GenreId = 1, Price = 99, ArtistId = "Skank", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "O Samba Poconé", GenreId = 1, Price = 99, ArtistId = "Skank", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "A-Sides", GenreId = 1, Price = 99, ArtistId = "Soundgarden", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Heart of the Night", GenreId = 2, Price = 99, ArtistId = "Spyro Gyra", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Morning Dance", GenreId = 2, Price = 99, ArtistId = "Spyro Gyra", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "In Step", GenreId = 6, Price = 99, ArtistId = "Stevie Ray Vaughan & Double Trouble", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Core", GenreId = 1, Price = 99, ArtistId = "Stone Temple Pilots", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Mezmerize", GenreId = 3, Price = 99, ArtistId = "System Of A Down", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Temple of the Dog", GenreId = 4, Price = 99, ArtistId = "Temple of the Dog", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "[1997] Black Light Syndrome", GenreId = 1, Price = 99, ArtistId = "Terry Bozzio, Tony Levin & Steve Stevens", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "South American Getaway", GenreId = 10, Price = 99, ArtistId = "The 12 Cellists of The Berlin Philharmonic", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live [Disc 1]", GenreId = 6, Price = 99, ArtistId = "The Black Crowes", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Live [Disc 2]", GenreId = 6, Price = 99, ArtistId = "The Black Crowes", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Beyond Good And Evil", GenreId = 1, Price = 99, ArtistId = "The Cult", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Doors", GenreId = 1, Price = 99, ArtistId = "The Doors", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "English Renaissance", GenreId = 10, Price = 99, ArtistId = "The King's Singers", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Police Greatest Hits", GenreId = 1, Price = 99, ArtistId = "The Police", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Every Kind of Light", GenreId = 1, Price = 99, ArtistId = "The Posies", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Hot Rocks, 1964-1971 (Disc 1)", GenreId = 1, Price = 99, ArtistId = "The Rolling Stones", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "No Security", GenreId = 1, Price = 99, ArtistId = "The Rolling Stones", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Voodoo Lounge", GenreId = 1, Price = 99, ArtistId = "The Rolling Stones", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "My Generation - The Very Best Of The Who", GenreId = 1, Price = 99, ArtistId = "The Who", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Serie Sem Limite (Disc 1)", GenreId = 7, Price = 99, ArtistId = "Tim Maia", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Serie Sem Limite (Disc 2)", GenreId = 7, Price = 99, ArtistId = "Tim Maia", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bach: Toccata & Fugue in D Minor", GenreId = 10, Price = 99, ArtistId = "Ton Koopman", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Achtung Baby", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "B-Sides 1980-1990", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "How To Dismantle An Atomic Bomb", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = 9, GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Rattle And Hum", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Best Of 1980-1990", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "War", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Zooropa", GenreId = 1, Price = 99, ArtistId = "U2", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "UB40 The Best Of - Volume Two [UK]", GenreId = 8, Price = 99, ArtistId = "UB40", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Diver Down", GenreId = 1, Price = 99, ArtistId = "Van Halen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "The Best Of Van Halen, Vol. I", GenreId = 1, Price = 99, ArtistId = "Van Halen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Van Halen III", GenreId = 1, Price = 99, ArtistId = "Van Halen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Van Halen", GenreId = 1, Price = 99, ArtistId = "Van Halen", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Axé Bahia 2001", GenreId = 9, Price = 99, ArtistId = "Various Artists", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Sambas De Enredo 2001", GenreId = 7, Price = 99, ArtistId = "Various Artists", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Vozes do MPB", GenreId = 7, Price = 99, ArtistId = "Various Artists", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Contraband", GenreId = 1, Price = 99, ArtistId = "Velvet Revolver", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Vinicius De Moraes", GenreId = 7, Price = 99, ArtistId = "Vinícius De Moraes", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bach: Goldberg Variations", GenreId = 10, Price = 99, ArtistId = "Wilhelm Kempff", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bartok: Violin & Viola Concertos", GenreId = 10, Price = 99, ArtistId = "Yehudi Menuhin", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Bach: The Cello Suites", GenreId = 10, Price = 99, ArtistId = "Yo-Yo Ma", AlbumArtUrl = "/Content/Images/placeholder.gif" },
// new Album { Title = "Ao Vivo [IMPORT]", GenreId = 7, Price = 99, ArtistId = "Zeca Pagodinho", AlbumArtUrl = "/Content/Images/placeholder.gif" }